export const PURGE_AUTH = 'PURGE_AUTH';
export const SET_AUTH = 'SET_AUTH';
export const SET_ERROR = 'SET_ERROR';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_UPDATE_ERROR = 'SET_PROFILE_UPDATE_ERROR';

export const SET_MODULES = 'SET_MODULES';
export const SET_CHAPTER = 'SET_CHAPTER';

export const GET_NEXT_FRAGMENT = 'GET_NEXT_FRAGMENT';
export const UPDATE_FRAGMENT_FORM = 'UPDATE_FRAGMENT_FORM';
export const UPDATE_FRAGMENT = 'UPDATE_FRAGMENT';
export const INIT_FRAGMENTS = 'INIT_FRAGMENTS';
export const SET_TASKS = 'SET_TASKS';
export const SET_FEEDBACK = 'SET_FEEDBACK';

export const SHOW_RATING_FRAGMENT = 'SHOW_RATING_FRAGMENT';

export const RESET_FORM_STATE = 'RESET_FORM_STATE';

export const SELECT_CHAPTER = 'SELECT_CHAPTER';
